default:

package:
	docker build -f ops/docker/alpine/Dockerfile -t kroki-builder-nomnoml:alpine -t kroki-builder-nomnoml:latest -t kroki-builder-nomnoml:0.3.0-alpine .
#	docker build -f ops/docker/slim-stretch/Dockerfile -t kroki-builder-nomnoml:slim-stretch .
