= Kroki Documentation
:uri-exoscale: https://www.exoscale.com/

[discrete.tagline]
=== Convert plain text diagrams to images !

Kroki provides a unified HTTP API with support for BlockDiag (BlockDiag, SeqDiag, ActDiag, NwDiag, PacketDiag, RackDiag),
BPMN, Bytefield, C4 (with PlantUML), Diagrams.net (experimental), Ditaa, Erd, Excalidraw, GraphViz, Mermaid, Nomnoml, PlantUML, Structurizr, SvgBob,
Symbolator, UMLet, Vega, Vega-Lite, WaveDrom and WireViz... and more to come!

Kroki is available as a Self-Managed instance. +
We are also _actively_ looking for sponsors to provide Kroki as a free service:

Self-Managed::
Select this option if you want to download and install Kroki on your own infrastructure or in our public cloud environment. +
Please refer to the xref:setup:install.adoc[documentation] to install Kroki.

Free service::
Thanks to {uri-exoscale}[Exoscale], which has kindly offered two servers, we can provide Kroki as a _free service_! +
However, some parts of the infrastructure are still host on other providers, so *we are still looking for sponsors to cover all the expenses*.
+
If you are interested, please 👋 mailto:hello@kroki.io[contact us].
+
NOTE: The public instance of Kroki does not do any remote call for performance and security reasons.
We also want to keep the API as simple as possible, so it takes a text diagram as input and returns an image.
