= Install Kroki
:uri-docker-kroki-image: https://hub.docker.com/r/yuzutech/kroki
:uri-docker-kroki-blockdiag-image: https://hub.docker.com/r/yuzutech/kroki-blockdiag
:uri-docker-kroki-mermaid-image: https://hub.docker.com/r/yuzutech/kroki-mermaid
:uri-docker-kroki-bpmn-image: https://hub.docker.com/r/yuzutech/kroki-bpmn
:uri-docker-kroki-excalidraw-image: https://hub.docker.com/r/yuzutech/kroki-excalidraw
:uri-blockdiag: http://blockdiag.com/en/blockdiag/index.html
:uri-seqdiag: http://blockdiag.com/en/seqdiag/index.html
:uri-actdiag: http://blockdiag.com/en/actdiag/index.html
:uri-nwdiag: http://blockdiag.com/en/nwdiag/index.html
:uri-rackdiag: http://blockdiag.com/en/nwdiag/rackdiag-examples.html
:uri-packetdiag: http://blockdiag.com/en/nwdiag/packetdiag-examples.html
:uri-mermaid: https://mermaidjs.github.io/
:uri-bpmn: https://bpmn.io/toolkit/bpmn-js/
:uri-excalidraw: https://excalidraw.com/
:uri-docker-get-started: https://docs.docker.com/get-started/
:uri-docker-compose-install: https://docs.docker.com/compose/install/
:uri-docker-container-networking: https://docs.docker.com/config/containers/container-networking/
:uri-podman-get-started: https://podman.io/getting-started/
:uri-podman-compose-install: https://github.com/containers/podman-compose
:uri-k8s-publish-service: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
:uri-k8s-definition-files: https://raw.githubusercontent.com/yuzutech/kroki/master/docs/modules/setup/examples/k8s

To convert plain text diagrams to images with Kroki,
you first need to install the gateway server.

[TIP]
====
We recommend installing Kroki using *Docker*, especially if you don't want to manually install diagrams libraries.

However, you can also install each diagrams libraries that you want to use and run the gateway server as a _standalone executable jar_.
Consult the xref:manual-install.adoc[manual install page] to find out how.
====

Assumptions:

* [x] {uri-docker-get-started}[Docker] is installed on your machine.
* [x] {uri-docker-compose-install}[Docker Compose] is installed on your machine (optional).

On this page, you'll learn:

* [x] How to run Kroki
* [x] How to configure Kroki

== Using Docker

[source,docker-cli]
docker run yuzutech/kroki

The above command will effectively start a server on port 8000. +
By default, when you start a container, it does not publish any of its ports to the outside world.
To make a port available to services outside of Docker, you need to use the `--publish` or `-p` flag.
For instance, if you want to map TCP port 8000 in the container to port 8080 on your host, use:

[source,docker-cli]
docker run -p8080:8000 yuzutech/kroki

With the above command, the server will be available on your host at: http://localhost:8080 +
You can read more about {uri-docker-container-networking}[container networking] in the Docker documentation.

Finally, to start a container in detached mode, you use `-d` option:

[source,docker-cli]
docker run -p8080:8000 -d yuzutech/kroki

== Using docker-compose

You can use `docker-compose` to run multiple containers.
Here's an example where we start all the containers, this time exposing host port 8000:

.docker-compose.yml
[source,yml]
----
include::example$kroki-docker-compose.yml[]
----

[source,docker-cli]
docker-compose up -d

== Using Podman

Podman is a drop-in replacement for Docker for Linux systems only, and is available for many distributions.
It is light-weight, does not need a daemon running in the background, and is built with container security in mind.

Using Podman is a useful intermediate development and testing step before lifting your Kroki implementation into Kubernetes.

== Using podman-compose
Use `podman-compose`, a helper program  just like docker-compose to run multiple containers without the Docker daemon.
This is a useful intermediate step before lifting your Kroki implementation into Kubernetes.

With Podman 3, there is support for Docker Compose if you want to use that

Assumptions:

* [x] {uri-podman-get-started}[Podman] is installed on your machine.
* [x] {uri-podman-compose-install}[Podman-compose] is installed on your machine.

Use the same docker-compose.yml file as in <<using-docker-compose>>.

[source,docker-cli]
podman-compose up -d

=== Images

{uri-docker-kroki-image}[yuzutech/kroki] image contains the following diagrams libraries out-of-the-box:

* https://bytefield-svg.deepsymmetry.org/[Bytefield]
* http://ditaa.sourceforge.net[Ditaa]
* https://github.com/BurntSushi/erd[Erd]
* https://www.graphviz.org/[GraphViz]
* https://github.com/skanaar/nomnoml[Nomnoml]
* https://github.com/plantuml/plantuml[PlantUML]
** https://github.com/RicardoNiepel/C4-PlantUML[C4 model] (with PlantUML)
* https://github.com/ivanceras/svgbob[Svgbob]
* https://github.com/umlet/umlet[UMlet]
* https://github.com/vega/vega[Vega]
* https://github.com/vega/vega-lite[Vega-Lite]
* https://wavedrom.com[WaveDrom]

In other words, the following endpoints will be available:

[literal]
....
/bytefield
/c4plantuml
/ditaa
/erd
/graphviz
/dot
/nomnoml
/plantuml
/svgbob
/umlet
/vega
/vegalite
/wavedrom
....

If you want to use _BlockDiag_, _ActDiag_, _NwDiag_, _SeqDiag_, _Mermaid_ or _BPMN_, then you will also need to start companion containers:

{uri-docker-kroki-blockdiag-image}[yuzutech/kroki-blockdiag^]::
Provides block, sequence, activity and network diagrams for Kroki using respectively
{uri-blockdiag}[BlockDiag^],
{uri-seqdiag}[SeqDiag^],
{uri-actdiag}[ActDiag^],
{uri-nwdiag}[NwDiag^]
{uri-packetdiag}[PacketDiag^],
and {uri-rackdiag}[RackDiag^] libraries.

{uri-docker-kroki-mermaid-image}[yuzutech/kroki-mermaid^]::
Provides flowchart, sequence and Gantt diagrams for Kroki using {uri-mermaid}[Mermaid^].

{uri-docker-kroki-bpmn-image}[yuzutech/kroki-bpmn^]::
Provides BPMN diagrams for Kroki using {uri-bpmn}[bpmn-js^].

{uri-docker-kroki-excalidraw-image}[yuzutech/kroki-excalidraw^]::
Provides BPMN diagrams for Kroki using {uri-excalidraw}[Excalidraw^].

== Using Kubernetes

This section will explain how to install Kroki on Kubernetes using the `default` namespace.

[IMPORTANT]
====
To allow external access to your Kroki internal service,
you will to publish the service using `ClusterIP`, `NodePort`, `LoadBalancer` or `ExternalName`.

In this example, we will use `Ingress` to expose the service on port 8000.

To learn more about how to publish a service, please consult the {uri-k8s-publish-service}[Kubernetes documentation]
====

You can link:{attachmentsdir}/kroki-k8s.zip[download a bundle (zip file)] that contains all the required `Deployment`, `Service` and `Ingress` definition files to deploy Kroki on Kubernetes.

Once you've downloaded the .zip file, extract the content of the zip file into a folder named _kroki-k8s_.

[TIP]
====
If you have `wget` and `unzip` installed on your machine, open a terminal and type:

[source,cli]
----
wget http://docs.kroki.io/kroki/setup/_attachments/kroki-k8s.zip -O kroki-k8s.zip
unzip kroki-k8s.zip -d kroki-k8s
----
The above commands will download the zip file and extract it into a folder named _kroki-k8s_.
====

Use the command `kubectl apply` to create all the required Kubernetes objects:

[source,cli]
----
kubectl apply -f /path/to/kroki-k8s
----

Do not forget to replace `/path/to/kroki-k8s` with the actual path to the folder that contains the definition files (`.yaml`)

Alternatively, you install them individually from GitHub, open a terminal and type:

.Add BlockDiag service
[source,cli,subs=+attributes]
----
kubectl apply -f {uri-k8s-definition-files}/blockdiag-deployment.yaml
kubectl apply -f {uri-k8s-definition-files}/blockdiag-service.yaml
----

.Add Mermaid service
[source,cli,subs=+attributes]
----
kubectl apply -f {uri-k8s-definition-files}/mermaid-deployment.yaml
kubectl apply -f {uri-k8s-definition-files}/mermaid-service.yaml
----

.Add BPMN service
[source,cli,subs=+attributes]
----
kubectl apply -f {uri-k8s-definition-files}/bpmn-deployment.yaml
kubectl apply -f {uri-k8s-definition-files}/bpmn-service.yaml
----

.Add Excalidraw service
[source,cli,subs=+attributes]
----
kubectl apply -f {uri-k8s-definition-files}/excalidraw-deployment.yaml
kubectl apply -f {uri-k8s-definition-files}/excalidraw-service.yaml
----

.Add Kroki service
[source,cli,subs=+attributes]
----
kubectl apply -f {uri-k8s-definition-files}/kroki-deployment.yaml
kubectl apply -f {uri-k8s-definition-files}/kroki-service.yaml
----

.Add Ingress
[source,cli,subs=+attributes]
kubectl apply -f {uri-k8s-definition-files}/kroki-ingress.yaml

Verify that Kroki service is running using `kubectl get pod`:

[source,cli]
kubectl get pod

If the installation was successful, the command should report a list of running pods:

....
NAME                          READY   STATUS    RESTARTS   AGE
blockdiag-7bd6c989b7-zhvj8    1/1     Running   0          24s
bpmn-6cfccf9bc4-6w4px         1/1     Running   0          24s
excalidraw-5b84995fcb-dh57t   1/1     Running   0          24s
kroki-6b49bcb7c4-x2ksc        1/1     Running   0          23s
mermaid-7bff5c9959-hkrxx      1/1     Running   0          22s
....

To make sure that Kroki is working, open a terminal and type:

[source,cli]
kubectl port-forward service/kroki 8000:8000

The above command will forward local port 8000 to port 8000 on the `service/kroki` Pod.
In other words, Kroki will be accessible on localhost:8000.

Open a second terminal and type:

[source,cli]
curl http://localhost:8000/seqdiag/svg/eNorTi1MyUxMV6jmUlBIKsovL04tUtC1UyhPTQKyyoCc6JzEpNQcBVsFJXfXEAX9zLyU1Aq9jJLcHKVYayQ9Nrq6CE3WhA0L8A8GmpaUk5-un5yfm5uaVwIxD6EWqDElsSQxKbE4FUmfp1-wa1CIAg49IFfANOFxXS0A68hQUg==

[NOTE]
=====
To uninstall Kroki, you can use the command `kubectl delete`:

[source,cli]
kubectl delete -f /path/to/kroki-k8s
=====
