= Install Kroki
:uri-docker-kroki-image: https://cloud.docker.com/u/yuzutech/repository/docker/yuzutech/kroki
:uri-docker-kroki-blockdiag-image: https://cloud.docker.com/u/yuzutech/repository/docker/yuzutech/kroki-blockdiag
:uri-docker-kroki-mermaid-image: https://cloud.docker.com/u/yuzutech/repository/docker/yuzutech/kroki-mermaid
:uri-blockdiag: http://blockdiag.com/en/blockdiag/index.html
:uri-seqdiag: http://blockdiag.com/en/seqdiag/index.html
:uri-actdiag: http://blockdiag.com/en/actdiag/index.html
:uri-nwdiag: http://blockdiag.com/en/nwdiag/index.html
:uri-nwdiag: http://blockdiag.com/en/nwdiag/index.html
:uri-rackdiag: http://blockdiag.com/en/nwdiag/rackdiag-examples.html
:uri-packetdiag: http://blockdiag.com/en/nwdiag/packetdiag-examples.html
:uri-mermaid: https://mermaidjs.github.io/
:uri-docker-get-started: https://docs.docker.com/get-started/
:uri-docker-compose-install: https://docs.docker.com/compose/install/
:uri-docker-container-networking: https://docs.docker.com/config/containers/container-networking/

To convert plain text diagrams to images with Kroki,
you first need to install the gateway server.

[TIP]
====
We recommend to install Kroki using *Docker*, especially if you don't want to manually install diagrams libraries.

However, you can also install each diagrams libraries that you want to use and run the gateway server as a _standalone executable jar_.
Consult the xref:manual-install.adoc[manual install page] to find out how.
====

Assumptions:

* [x] {uri-docker-get-started}[Docker] is installed on your machine.
* [x] {uri-docker-compose-install}[Docker Compose] is installed on your machine (optional).

On this page, you'll learn:

* [x] How to run Kroki
* [x] How to configure Kroki

== Using Docker

[source,docker-cli]
docker run yuzutech/kroki

The above command will effectively start a server on port 8000. +
By default, when you start a container, it does not publish any of its ports to the outside world.
To make a port available to services outside of Docker, you need to use the `--publish` or `-p` flag.
For instance, if you want to map TCP port 8000 in the container to port 8080 on your host, use:

[source,docker-cli]
docker run -p8080:8000 yuzutech/kroki

With the above command, the server will be available on your host at: http://localhost:8080 +
You can read more about {uri-docker-container-networking}[container networking] in the Docker documentation.

Finally, to start a container in detached mode, you use `-d` option:

[source,docker-cli]
docker run -p8080:8000 -d yuzutech/kroki

=== Images

{uri-docker-kroki-image}[yuzutech/kroki] image contains the following diagrams libraries out-of-the-box:

* http://ditaa.sourceforge.net[Ditaa]
* https://github.com/BurntSushi/erd[Erd]
* https://www.graphviz.org/[GraphViz]
* https://github.com/skanaar/nomnoml[Nomnoml]
* https://github.com/plantuml/plantuml[PlantUML]
** https://github.com/RicardoNiepel/C4-PlantUML[C4 model] (with PlantUML)
* https://github.com/ivanceras/svgbob[Svgbob]
* https://github.com/umlet/umlet[UMlet]
* https://github.com/vega/vega[Vega]
* https://github.com/vega/vega-lite[Vega-Lite]

In other words, the following endpoints will be available:

```
/c4plantuml
/ditaa
/erd
/graphviz
/dot
/nomnoml
/plantuml
/svgbob
/umlet
/vega
/vegalite
```

If you want to use _BlockDiag_, _ActDiag_, _NwDiag_, _SeqDiag_ or _Mermaid_, then you will also need to start companion containers:

{uri-docker-kroki-blockdiag-image}[yuzutech/kroki-blockdiag]::
Provides block, sequence, activity and network diagrams for Kroki using respectively
{uri-blockdiag}[BlockDiag],
{uri-seqdiag}[SeqDiag],
{uri-actdiag}[ActDiag],
{uri-nwdiag}[NwDiag]
{uri-packetdiag}[PacketDiag],
and {uri-rackdiag}[RackDiag] libraries.

{uri-docker-kroki-mermaid-image}[yuzutech/kroki-mermaid]::
Provides flowchart, sequence and Gantt diagrams for Kroki using {uri-mermaid}[Mermaid].

You can use `docker-compose` to run multiple containers.
Here's an example where we start all the containers:

.docker-compose.yml
```yml
version: "3"
services:
 core:
   image: yuzutech/kroki
   environment:
     - KROKI_BLOCKDIAG_HOST=blockdiag
     - KROKI_MERMAID_HOST=mermaid
   ports:
     - "8000:8000"
 blockdiag:
   image: yuzutech/kroki-blockdiag
   ports:
     - "8001:8001"
 mermaid:
   image: yuzutech/kroki-mermaid
   ports:
     - "8002:8002"
```

[source,docker-cli]
docker-compose up -d
