= Install Kroki
// Docker Hub URIs of Kroki container images
:uri-docker-kroki-image: https://hub.docker.com/r/yuzutech/kroki
:uri-docker-kroki-mermaid-image: https://hub.docker.com/r/yuzutech/kroki-mermaid
:uri-docker-kroki-bpmn-image: https://hub.docker.com/r/yuzutech/kroki-bpmn
:uri-docker-kroki-excalidraw-image: https://hub.docker.com/r/yuzutech/kroki-excalidraw
:uri-docker-kroki-diagramsnet-image: https://hub.docker.com/r/yuzutech/kroki-diagramsnet
:uri-docker-kroki-wireviz-image: https://hub.docker.com/r/yuzutech/kroki-wireviz
// URIs of diagram generation application sites by diagram name
:uri-blockdiag: http://blockdiag.com/en/blockdiag/index.html
:uri-seqdiag: http://blockdiag.com/en/seqdiag/index.html
:uri-actdiag: http://blockdiag.com/en/actdiag/index.html
:uri-nwdiag: http://blockdiag.com/en/nwdiag/index.html
:uri-rackdiag: http://blockdiag.com/en/nwdiag/rackdiag-examples.html
:uri-packetdiag: http://blockdiag.com/en/nwdiag/packetdiag-examples.html
:uri-mermaid: https://mermaidjs.github.io/
:uri-bpmn: https://bpmn.io/toolkit/bpmn-js/
:uri-excalidraw: https://excalidraw.com/
:uri-diagramsnet: https://diagrams.net/
:uri-wireviz: https://github.com/formatc1702/WireViz

This section covers installing Kroki locally.

On this page, you'll learn:

* [x] How to get started
* [x] The different ways to install Kroki
* [x] About the Kroki pre-built image containers and the diagrams they provide

== Get started

Use either xref:#docker-podman[Docker or Podman] as the easiest and fastest method to get started running Kroki locally on a system with Internet access using the pre-built Kroki containers published on Docker Hub.

Start the mandatory <<#yuzutech-kroki,`yuzutech/kroki`>> container only to use a large number of diagram libraries immediately including PlantUML, GraphViz and more.
Depending on your diagram needs, this may be enough.

For the lists of diagram libraries pre-installed in each container see the <<kroki-container-images,Kroki container images>> section on this page.

NOTE: All the companion containers are _optional_.
Only the <<yuzutech-kroki,yuzutech-kroki>> container is mandatory.

[#docker-podman]
== Docker or Podman
We recommend installing Kroki using containers with either Docker or Podman, especially if you don't want to manually install diagrams libraries.

Read more about choosing between Docker or Podman on the xref:about-docker-podman.adoc[] page.

Find how to install Kroki using Docker or Podman on the xref:use-docker-or-podman.adoc[] page.

== Kubernetes
Find how to make a Kubernetes installation on the xref:use-kubernetes.adoc[] page.

== Manual installation
You can also make a customized manual installation that suits your needs.

To do this, you will need to manually install the Kroki gateway server as a _standalone executable jar_, install each diagram library that you want to use, then run the gateway server jar file.

You are responsible for managing diagram library installations on your system.

Find how to make a manual installation on the xref:manual-install.adoc[Manual installation] page.

[#images]
== [[kroki-container-images]]Kroki container images
Kroki container images are published on the https://hub.docker.com/u/yuzutech[Docker Hub] registry and are the:

* Mandatory <<The "kroki" container,"kroki" container>> that provides the gateway server and a large number of diagrams.
* _Optional_ <<Companion containers,companion containers>> that provide additional diagrams.
  Please note that you need the gateway server to interact with them.

== [[yuzutech-kroki]]The "kroki" container
The `yuzutech/kroki` container is the only container that must be running for a minimal install.

The {uri-docker-kroki-image}[yuzutech/kroki] image contains the gateway server, and the following diagram libraries out-of-the-box:

* https://bytefield-svg.deepsymmetry.org/[Bytefield]
* https://github.com/terrastruct/d2[D2]
* http://ditaa.sourceforge.net[Ditaa]
* https://github.com/BurntSushi/erd[Erd]
* https://www.graphviz.org/[GraphViz]
* https://github.com/skanaar/nomnoml[Nomnoml]
* https://github.com/drhsqlite/pikchr[Pikchr]
* https://github.com/plantuml/plantuml[PlantUML] including https://github.com/RicardoNiepel/C4-PlantUML[C4 model]
* https://github.com/structurizr/dsl[Structurizr]
* https://github.com/ivanceras/svgbob[Svgbob]
* https://github.com/hdl/symbolator[Symbolator]
* https://github.com/umlet/umlet[UMlet]
* https://github.com/vega/vega[Vega]
* https://github.com/vega/vega-lite[Vega-Lite]
* https://wavedrom.com[WaveDrom]

In other words, the following endpoints will be available:

[literal]
....
/actdiag
/blockdiag
/bytefield
/c4plantuml
/d2
/ditaa
/erd
/graphviz
/dot
/nomnoml
/nwdiag
/packetdiag
/pikchr
/plantuml
/rackdiag
/seqdiag
/structurizr
/svgbob
/symbolator
/umlet
/vega
/vegalite
/wavedrom
....

If you want to use additional diagram libraries (such as _BPMN_, _Excalidraw_ or _Mermaid_), then you will also need to start their companion containers:

== Companion containers
These optional companion containers provide additional diagrams and require the gateway server

// * <<yuzutech-kroki-bpmn,Kroki bpmn>>
// * <<yuzutech-kroki-excalidraw,Kroki excalidraw>>
// * <<yuzutech-kroki-mermaid,Kroki mermaid>>
// * <<yuzutech-kroki-wireviz,Kroki wireviz>>

[#yuzutech-kroki-bpmn]
{uri-docker-kroki-bpmn-image}[yuzutech/kroki-bpmn^]::
Provides BPMN diagrams for Kroki using the {uri-bpmn}[bpmn-js^] library.

[#yuzutech-kroki-excalidraw]
{uri-docker-kroki-excalidraw-image}[yuzutech/kroki-excalidraw^]::
Provides hand-drawn diagrams for Kroki using the {uri-excalidraw}[Excalidraw^] library.

[#yuzutech-kroki-mermaid]
{uri-docker-kroki-mermaid-image}[yuzutech/kroki-mermaid^]::
Provides flowchart, sequence and Gantt diagrams for Kroki using the {uri-mermaid}[Mermaid^] library.

[#yuzutech-kroki-diagramsnet]
{uri-docker-kroki-diagramsnet-image}[yuzutech/kroki-diagramsnet^]  (experimental)::
Provides diagrams for Kroki using the {uri-diagramsnet}[diagrams.net^] library.

[#yuzutech-kroki-wireviz]
{uri-docker-kroki-wireviz-image}[yuzutech/kroki-wireviz^]::
Provides diagrams for Kroki using the {uri-wireviz}[WireViz^] library.
