= Install Kroki
:uri-docker-kroki-image: https://hub.docker.com/r/yuzutech/kroki
:uri-docker-kroki-blockdiag-image: https://hub.docker.com/r/yuzutech/kroki-blockdiag
:uri-docker-kroki-mermaid-image: https://hub.docker.com/r/yuzutech/kroki-mermaid
:uri-docker-kroki-bpmn-image: https://hub.docker.com/r/yuzutech/kroki-bpmn
:uri-docker-kroki-excalidraw-image: https://hub.docker.com/r/yuzutech/kroki-excalidraw
:uri-blockdiag: http://blockdiag.com/en/blockdiag/index.html
:uri-seqdiag: http://blockdiag.com/en/seqdiag/index.html
:uri-actdiag: http://blockdiag.com/en/actdiag/index.html
:uri-nwdiag: http://blockdiag.com/en/nwdiag/index.html
:uri-rackdiag: http://blockdiag.com/en/nwdiag/rackdiag-examples.html
:uri-packetdiag: http://blockdiag.com/en/nwdiag/packetdiag-examples.html
:uri-mermaid: https://mermaidjs.github.io/
:uri-bpmn: https://bpmn.io/toolkit/bpmn-js/
:uri-excalidraw: https://excalidraw.com/
:uri-docker-get-started: https://docs.docker.com/get-started/
:uri-podman-get-started: https://podman.io/getting-started/
:uri-docker-compose-install: https://docs.docker.com/compose/install/
:uri-podman-compose-install: https://github.com/containers/podman-compose
:uri-docker-container-networking: https://docs.docker.com/config/containers/container-networking/
:uri-podman-container-networking: https://podman.io/getting-started/network
:uri-k8s-publish-service: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
:uri-k8s-definition-files: https://raw.githubusercontent.com/yuzutech/kroki/master/docs/modules/setup/examples/k8s
:uri-localhost-8000: pass:q[`http://localhost:8000[http://localhost:**8000**]`]
:uri-localhost-8080: pass:q[`http://localhost:8080[http://localhost:80**80**]`]

To convert plain text diagrams to images with Kroki,
you first need to install the gateway server.

[TIP]
====
We recommend installing Kroki using containers with either *Docker* or *Podman*, especially if you don't want to manually install diagrams libraries.
Read more about choosing Docker or Podman on this page in <<about-docker-and-podman-for-kroki>>.

However, you can also install each diagrams libraries that you want to use and run the gateway server as a _standalone executable jar_.
Consult the xref:manual-install.adoc[manual install page] to find out how.
====

On this page, you'll learn:

* [x] How to run Kroki
* [x] How to configure Kroki

== Installing the Kroki gateway server
Installing and running the Kroki gateway server by itself gets you started quickly to begin creating diagrams provided by the <<yuzutech-kroki,yuzutech/kroki image>>.

Assumptions:

* [x] {uri-docker-get-started}[Docker] or {uri-podman-get-started}[Podman] is installed on your machine.

To start the Kroki gateway server on its default port 8000, run the command:

* _Using docker:_
+
[source,docker-cli,subs=+quotes]
*docker* run yuzutech/kroki

* _Using podman:_
+
[source,podman-cli,subs=+quotes]
*podman* run yuzutech/kroki

After the above command, the server will be available on your host at: {uri-localhost-8000}

*Mapping a different port*

By default, when you start a container, it does not publish any of its ports to the outside world.
To make a port available to services outside of Docker or Podman, you need to use the `--publish` or `-p` flag.
For instance, if you want to your host's TCP port 8080 to the TCP port 8000 of the kroki container, use:

* _Using docker:_
+
[source,docker-cli,subs=+quotes]
docker run *-p8080:8000* yuzutech/kroki

* _Using podman:_
+
[source,docker-cli,subs=+quotes]
podman run *-p8080:8000* yuzutech/kroki

After the above command, the server will be available on your host at: {uri-localhost-8080}

You can read more about {uri-docker-container-networking}[Docker container networking] and {uri-podman-container-networking}[Podman networking] in their documentation.

*Detached mode*

The previous methods above ran the containers in the foreground, requiring you to press control-c to stop them.
Starting containers in detached mode runs them in the background, requiring you to use the Docker/Podman `stop` or `kill` command to stop them.

Finally, to start a container in detached mode, you use `-d` option:

* _Using docker:_
+
[source,docker-cli,subs=+quotes]
docker run -p8080:8000 **-d** yuzutech/kroki

* _Using podman:_
+
[source,docker-cli,subs=+quotes]
podman run -p8080:8000 **-d** yuzutech/kroki

After the above command, the server will be available on your host at: {uri-localhost-8080}

== Run multiple Kroki containers together

Running multiple containers allows you to use all the diagram features of Kroki in your environment provided by the <<images>>.
The gateway server container provided by the image <<yuzutech-kroki,yuzutech/kroki image>> is the minimum requirement.

*Example of running them all together*

Here's an example where we start all the Kroki containers together as a group (or pod) in detached mode.
This time host port 8000 is exposed, instead of port 8080 as used by the gateway server example above.

.docker-compose.yml
[source,yml]
----
include::example$kroki-docker-compose.yml[]
----

The methods below run Kroki's multiple containers using the same Kroki `docker-compose` yaml configuration file above.

*Use Docker or Podman with Docker Compose*

Assumptions:

* [x] {uri-docker-get-started}[Docker] *or* {uri-podman-get-started}[Podman 3] is installed on your machine.
      Note the mutual exclusivity.
* [x] {uri-docker-compose-install}[Docker Compose] is installed

Run:

    docker-compose up -d

*Use Podman with podman-compose*

Assumptions:

* [x] {uri-podman-get-started}[Podman] is installed on your machine.
* [x] {uri-podman-compose-install}[Podman-Compose] is installed on your machine.

Run:

    podman-compose up -d

*Testing after starting*

After starting the containers the servers will be available on your host at: {uri-localhost-8080}

== About Docker and Podman for Kroki
In this section you will learn:

* [x] Scenarios for running Kroki with Docker or Podman
* [x] A high level view of Docker and Podman

*Rough considerations when choosing Docker or Podman*

Considerations for using Docker:

* You are running Windows and just want to have Kroki running at home on your own machine or server.
* Docker is already installed on your linux system.

Considerations for using Podman:

* Running containers and pods of containers on Linux
* Cyber security and security by design
* Organizational deployments
* Learning about containers and pods on Linux
* Testing Kroki before lifting to Kubernetes

*About {uri-docker-get-started}[Docker] and {uri-docker-compose-install}[Docker Compose]:*
Docker runs containers using a client server architecture, with a background daemon.
Docker Compose starts multiple containers together.
The Docker Compose yaml configuration file is a standard way to describe a set of containers that must be started together.

*About {uri-podman-get-started}[Podman]:*
Podman is a drop-in replacement for Docker on Linux systems only and is available for many distributions.
It is light-weight in not needing a background daemon always running running in the background, and is built with container security in mind being able to be run as a normal user as well as root.
For enterprise deployments it is a useful step in learning to deploy, run and test pods on containers in a linux environment before lifting your Kroki implementation into a Kubernetes environment.
Using Docker Compose to support Podman requires Podman 3.

*About {uri-podman-compose-install}[Podman-compose]:*
Podman-compose is a scripted implementation of docker-compose with a Podman backend.
Its objective is to be able to run docker-compose.yml unmodified and rootless.
It provides a drop-in replacement for docker-compose.
Using podman-compose requires Podman.

=== Images

[#yuzutech-kroki]
{uri-docker-kroki-image}[yuzutech/kroki] image contains the following diagrams libraries out-of-the-box:

* https://bytefield-svg.deepsymmetry.org/[Bytefield]
* http://ditaa.sourceforge.net[Ditaa]
* https://github.com/BurntSushi/erd[Erd]
* https://www.graphviz.org/[GraphViz]
* https://github.com/skanaar/nomnoml[Nomnoml]
* https://github.com/plantuml/plantuml[PlantUML]
** https://github.com/RicardoNiepel/C4-PlantUML[C4 model] (with PlantUML)
* https://github.com/ivanceras/svgbob[Svgbob]
* https://github.com/umlet/umlet[UMlet]
* https://github.com/vega/vega[Vega]
* https://github.com/vega/vega-lite[Vega-Lite]
* https://wavedrom.com[WaveDrom]

In other words, the following endpoints will be available:

[literal]
....
/bytefield
/c4plantuml
/ditaa
/erd
/graphviz
/dot
/nomnoml
/plantuml
/svgbob
/umlet
/vega
/vegalite
/wavedrom
....

If you want to use _BlockDiag_, _ActDiag_, _NwDiag_, _SeqDiag_, _Mermaid_ or _BPMN_, then you will also need to start companion containers:

[#yuzutech-kroki-blockdiag]
{uri-docker-kroki-blockdiag-image}[yuzutech/kroki-blockdiag^]::
Provides block, sequence, activity and network diagrams for Kroki using respectively
{uri-blockdiag}[BlockDiag^],
{uri-seqdiag}[SeqDiag^],
{uri-actdiag}[ActDiag^],
{uri-nwdiag}[NwDiag^]
{uri-packetdiag}[PacketDiag^],
and {uri-rackdiag}[RackDiag^] libraries.

[#yuzutech-kroki-mermaid]
{uri-docker-kroki-mermaid-image}[yuzutech/kroki-mermaid^]::
Provides flowchart, sequence and Gantt diagrams for Kroki using {uri-mermaid}[Mermaid^].

[#yuzutech-kroki-bpmn]
{uri-docker-kroki-bpmn-image}[yuzutech/kroki-bpmn^]::
Provides BPMN diagrams for Kroki using {uri-bpmn}[bpmn-js^].

[#yuzutech-kroki-excalidraw]
{uri-docker-kroki-excalidraw-image}[yuzutech/kroki-excalidraw^]::
Provides BPMN diagrams for Kroki using {uri-excalidraw}[Excalidraw^].

== Using Kubernetes

This section will explain how to install Kroki on Kubernetes using the `default` namespace.

[IMPORTANT]
====
To allow external access to your Kroki internal service,
you will to publish the service using `ClusterIP`, `NodePort`, `LoadBalancer` or `ExternalName`.

In this example, we will use `Ingress` to expose the service on port 8000.

To learn more about how to publish a service, please consult the {uri-k8s-publish-service}[Kubernetes documentation]
====

You can link:{attachmentsdir}/kroki-k8s.zip[download a bundle (zip file)] that contains all the required `Deployment`, `Service` and `Ingress` definition files to deploy Kroki on Kubernetes.

Once you've downloaded the .zip file, extract the content of the zip file into a folder named _kroki-k8s_.

[TIP]
====
If you have `wget` and `unzip` installed on your machine, open a terminal and type:

[source,cli]
----
wget http://docs.kroki.io/kroki/setup/_attachments/kroki-k8s.zip -O kroki-k8s.zip
unzip kroki-k8s.zip -d kroki-k8s
----
The above commands will download the zip file and extract it into a folder named _kroki-k8s_.
====

Use the command `kubectl apply` to create all the required Kubernetes objects:

[source,cli]
----
kubectl apply -f /path/to/kroki-k8s
----

Do not forget to replace `/path/to/kroki-k8s` with the actual path to the folder that contains the definition files (`.yaml`)

Alternatively, you install them individually from GitHub, open a terminal and type:

.Add BlockDiag service
[source,cli,subs=+attributes]
----
kubectl apply -f {uri-k8s-definition-files}/blockdiag-deployment.yaml
kubectl apply -f {uri-k8s-definition-files}/blockdiag-service.yaml
----

.Add Mermaid service
[source,cli,subs=+attributes]
----
kubectl apply -f {uri-k8s-definition-files}/mermaid-deployment.yaml
kubectl apply -f {uri-k8s-definition-files}/mermaid-service.yaml
----

.Add BPMN service
[source,cli,subs=+attributes]
----
kubectl apply -f {uri-k8s-definition-files}/bpmn-deployment.yaml
kubectl apply -f {uri-k8s-definition-files}/bpmn-service.yaml
----

.Add Excalidraw service
[source,cli,subs=+attributes]
----
kubectl apply -f {uri-k8s-definition-files}/excalidraw-deployment.yaml
kubectl apply -f {uri-k8s-definition-files}/excalidraw-service.yaml
----

.Add Kroki service
[source,cli,subs=+attributes]
----
kubectl apply -f {uri-k8s-definition-files}/kroki-deployment.yaml
kubectl apply -f {uri-k8s-definition-files}/kroki-service.yaml
----

.Add Ingress
[source,cli,subs=+attributes]
kubectl apply -f {uri-k8s-definition-files}/kroki-ingress.yaml

Verify that Kroki service is running using `kubectl get pod`:

[source,cli]
kubectl get pod

If the installation was successful, the command should report a list of running pods:

....
NAME                          READY   STATUS    RESTARTS   AGE
blockdiag-7bd6c989b7-zhvj8    1/1     Running   0          24s
bpmn-6cfccf9bc4-6w4px         1/1     Running   0          24s
excalidraw-5b84995fcb-dh57t   1/1     Running   0          24s
kroki-6b49bcb7c4-x2ksc        1/1     Running   0          23s
mermaid-7bff5c9959-hkrxx      1/1     Running   0          22s
....

To make sure that Kroki is working, open a terminal and type:

[source,cli]
kubectl port-forward service/kroki 8000:8000

The above command will forward local port 8000 to port 8000 on the `service/kroki` Pod.
In other words, Kroki will be accessible on localhost:8000.

Open a second terminal and type:

[source,cli]
curl http://localhost:8000/seqdiag/svg/eNorTi1MyUxMV6jmUlBIKsovL04tUtC1UyhPTQKyyoCc6JzEpNQcBVsFJXfXEAX9zLyU1Aq9jJLcHKVYayQ9Nrq6CE3WhA0L8A8GmpaUk5-un5yfm5uaVwIxD6EWqDElsSQxKbE4FUmfp1-wa1CIAg49IFfANOFxXS0A68hQUg==

[NOTE]
=====
To uninstall Kroki, you can use the command `kubectl delete`:

[source,cli]
kubectl delete -f /path/to/kroki-k8s
=====
