= Manual Install
:uri-gh-releases: https://github.com/yuzutech/kroki/releases

Assumptions:

* [x] You've Linux experience.
* [x] You've installed Java 8 on your Linux machine.

On this page, you'll learn:

* [x] How to run Kroki
* [x] How to configure Kroki

== Download and Run Kroki

You can download the latest _standalone executable jar_ from the GitHub {uri-gh-releases}[releases page].

Once you've downloaded the _jar_ file, open a terminal an type:

[source,java-cli]
java -jar kroki-server.jar

The above command will start a web server on port `8000`.
You can change the port using an environment variable, or a Java system property named `KROKI_PORT`.

[IMPORTANT]
====
The Kroki server only includes the following JVM-based diagrams libraries:

* http://ditaa.sourceforge.net[Ditaa]
* https://github.com/plantuml/plantuml[PlantUML] including https://github.com/RicardoNiepel/C4-PlantUML[C4 model]
* https://github.com/structurizr/dsl[Structurizr]
* https://github.com/umlet/umlet[UMlet]

If you want to use additional diagram libraries, you will either need to install them manually on your system or use xref:install.adoc#docker-podman[Docker or Podman].
====

== Learn more

- xref:configuration.adoc[Configure Kroki]
