= Manual Install
:uri-gh-releases: https://github.com/yuzutech/kroki/releases

Assumptions:

* [x] You've Linux experience.
* [x] You've installed Java 11 or greater on your Linux machine.

On this page, you'll learn:

* [x] How to run Kroki
* [x] How to configure Kroki

== Download and Run Kroki

You can download the latest _standalone executable jar_ from the GitHub {uri-gh-releases}[releases page].

Once you've downloaded the _jar_ file, open a terminal and type:

[source,java-cli]
java -jar kroki-server.jar

The above command will start a web server on port `8000`.
You can change the port using an environment variable, or a Java system property named `KROKI_PORT`.

[IMPORTANT]
====
The Kroki server does _not_ include diagram libraries! +
You will either need to install them manually on your system or use xref:install.adoc#docker-podman[Docker or Podman].

For instance, you can install GraphViz manually on your system (i.e., `dot` binary) and configure the path using a system property:

[source,java-cli]
java -DKROKI_DOT_BIN_PATH=/path/to/dot -jar kroki-server.jar
====

== Learn more

- xref:configuration.adoc[Configure Kroki]
