= Third Party Tools
:url-diagramit: https://diagramit.herokuapp.com/
:url-intellij-asciidoc-plugin: https://github.com/asciidoctor/asciidoctor-intellij-plugin/
:url-keenwrite: https://github.com/DaveJarvis/keenwrite/
:url-niolesk: https://niolesk.top/
:url-vscode: https://code.visualstudio.com/
:url-vscode-asciidoctor: https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode
:url-vscode-asciidoc-slides: https://marketplace.visualstudio.com/items?itemName=flobilosaurus.vscode-asciidoc-slides
:url-vscode-markdown-kroki: https://marketplace.visualstudio.com/items?itemName=pomdtr.markdown-kroki
:url-gitlab: https://about.gitlab.com/
:url-gitlab-int: https://docs.gitlab.com/ce/administration/integration/kroki.html
:url-sphinx: https://www.sphinx-doc.org/
:url-sphinx-int: https://github.com/sphinx-contrib/kroki
:url-julia: https://julialang.org
:url-julia-documenter: https://juliadocs.github.io/Documenter.jl/stable
:url-julia-int: https://bauglir.github.io/Kroki.jl/stable
:url-julia-pluto: https://github.com/fonsp/Pluto.jl
:url-julia-vscode: https://www.julia-vscode.org
:url-mkdocs-plugin: https://pypi.org/project/mkdocs-kroki-plugin/

A list of third party tools, developed by the community, that rely on Kroki.

== Diagram it

{url-diagramit}[A public service] that allows you to generate diagrams directly from a public source file.

[TIP]
====
You can use this service to generate diagrams from public URL. +
For instance: https://diagramit.herokuapp.com/v1/vega/generate?source=https://github.com/yuzutech/kroki/blob/main/tests/smoke/diagrams/bar-chart.vega

Here, we generate a Vega diagram from a public GitHub URL: https://github.com/yuzutech/kroki/blob/main/tests/smoke/diagrams/bar-chart.vega
====

== IntelliJ AsciiDoc Plugin

{url-intellij-asciidoc-plugin}[A plugin for the IntelliJ platform] (IntelliJ IDEA, RubyMine, etc.) that provides support for the AsciiDoc markup language.
The preview supports rendering diagrams using Kroki.

== KeenWrite

{url-keenwrite}[A Java-based desktop text editor] with live preview, string interpolation, and formulas.

== Niolesk

{url-niolesk}[An online editor] for Kroki.

[TIP]
====
Add any Kroki URL after `https://niolesk.top/#` and you'll be able to edit your diagram.

Here's an example: https://niolesk.top/#https://kroki.io/plantuml/svg/eNpTLMlIzU1VyM3MK6nk4nLKT9K1c8zJTE61UvBIzcnJVwQArksKZQ==
====

== VS-Code

The following {url-vscode}[Visual Studio Code] plugins support Kroki:

 * {url-vscode-asciidoctor}[AsciiDoc]
 * {url-vscode-asciidoc-slides}[AsciiDoc Slides]
 * {url-vscode-markdown-kroki}[Markdown Kroki]

== Gitlab

{url-gitlab}[Gitlab] can {url-gitlab-int}[use Kroki to render images] in Markdown, AsciiDoc, reST and Textile documents.

== Sphinx Documentation

There is an {url-sphinx-int}[Kroki integration] for the {url-sphinx}[Sphinx documentation generator].

== Julia

The {url-julia-int}[Kroki.jl] package provides integrations for the {url-julia}[Julia programming language].
It enables rendering diagrams in environments such as {url-julia-documenter}[Documenter.jl], {url-julia-pluto}[Pluto notebooks] and Julia's {url-julia-vscode}[Visual Studio Code integration].

== MkDocs

The {url-mkdocs-plugin}[MkDocs Kroki plugin] allows to embed Kroki diagrams within Markdown files processed by MkDocs.
