= Usage

Assumptions:

* [x] You have a running instance of Kroki.

On this page, you'll learn:

* [x] How to convert diagrams with Kroki

== Convert Diagrams

Kroki handles both `GET` and `POST` requests.
When using `GET` requests, your diagram must be encoded in the URL using a deflate + base64 algorithm.

NOTE: Don't worry, if you're not familiar with deflate or base64 (or if you don't want to use them),
you can also send your diagram as plain text using <<post-request,`POST` requests>>.

Let's take an example with a _GraphViz_ "Hello World":

.hello.txt
[source,txt]
----
digraph G {
  Hello->World
}
----

Here we are using a Python one-liner to encode our diagram using deflate + base64:

[source,cmd]
cat hello.txt | python -c "import sys; import base64; import zlib; print(base64.urlsafe_b64encode(zlib.compress(sys.stdin.read(), 9)))"

The above command will return `eNpLyUwvSizIUHBXqPZIzcnJ17ULzy_KSanlAgB1EAjQ`.
We can then copy this value in the URL:

 GET /graphviz/svg/eNpLyUwvSizIUHBXqPZIzcnJ17ULzy_KSanlAgB1EAjQ

And here's the result:

image::graphviz-hello-world.svg[]

[[post-request]]
You can also call Kroki with `POST`:

 POST /

```json
{
  "diagram_source": "digraph G {Hello->World}",
  "diagram_type": "graphviz",
  "output_format": "svg"
}
```

In this case, you don't need to encode your diagram.

It's also possible to send your diagram as plain text using the `Content-Type` header.
The output format will be specified using the `Accept` header and the diagram source will be sent as the request body:

 POST /graphviz

[source,plain]
----
Accept: image/svg+xml
Content-Type: text/plain

digraph G {
  Hello->World
}
----

You can also define the output format in the URL if you don't want to add an `Accept` header:

 POST /graphviz/svg
[source,plain]
----
Content-Type: text/plain

digraph G {
  Hello->World
}
----

The same concept applies when sending the diagram as JSON:

 POST /graphviz/svg
```json
{
  "diagram_source": "digraph G {Hello->World}"
}
```

== Command Line Interface (CLI)

Using https://curl.haxx.se/[_cURL_] to interact with the API is straightforward, open a terminal and type:

[source,cmd]
curl https://demo.kroki.io/graphviz/svg --data-raw 'digraph G {Hello->World}'

Or if you are more familiar with https://httpie.org/[_HTTPie_], you can send a JSON request:

[source,cmd]
http https://demo.kroki.io/ diagram_type='graphviz' output_format='svg' diagram_source='digraph G {Hello->World}'

It's also possible to send a file, for instance an Entity Relationship Diagram named project.erd:

```erd
[Person]
*name
height
weight
+birth_location_id

[Location]
*id
city
state
country

Person *--1 Location
```

[source,cmd]
curl https://demo.kroki.io/erd/svg --data-binary '@project.erd'

[source,cmd]
cat project.erd | http https://demo.kroki.io/erd/svg Content-Type:text/plain
