= Kroki server

Kroki server acts as a gateway and provides a unified API on-top of diagrams libraries.

== How to update third-party dependencies

=== Ditaa (mini)

Since https://github.com/stathissideris/ditaa is unmaintained, we are using an active fork: https://github.com/yuzutech/ditaa-mini which is based on an active fork https://github.com/pepijnve/ditaa.

We are producing native binaries with GraalVM: https://github.com/yuzutech/ditaa-mini/releases.

When a new version is available, we need to :

. update the fork
. run the following workflow: https://github.com/yuzutech/ditaa-mini/actions/workflows/native-image-on-demand.yml
. update the argument variable `ARG DITAA_VERSION="x.y.z"` in `server/ops/docker/jdk11-jammy/Dockerfile`

=== PlantUML

We are producing native binaries with GraalVM: https://github.com/ggrossetie/plantuml/releases

When a new version is available, we need to:

. update the fork
. run the following workflow: https://github.com/ggrossetie/plantuml/actions/workflows/native-image-on-demand.yml
. update the argument variable `ARG PLANTUML_VERSION="x.y.z"` in `server/ops/docker/jdk11-jammy/Dockerfile`

=== UMLet

We are producing native binaries with GraalVM: https://github.com/yuzutech/umlet/releases

When a new version is available, we need to:

. update the fork
. run the following workflow: https://github.com/yuzutech/umlet/actions/workflows/release.yml
. update the argument variable `ARG UMLET_VERSION="x.y.z"` in `server/ops/docker/jdk11-jammy/Dockerfile`

=== Symbolator

Since https://github.com/kevinpt/symbolator is unmaintained, we are using the fork: https://github.com/hdl/symbolator. It is also unmaintained, but has a few fixes that are not in the original repository.

We also replace the https://github.com/kevinpt/hdlparse dependency with a forked version from https://github.com/hdl/pyHDLParser. These two are also unmaintained.

As none of the forks publish their packages to pypi we build them from github. They also do not release versions so we select a version by a commit hash.

Should a new version become avalable, we need to:

. update the argument variable `ARG SYMBOLATOR_SOURCE` and `ARG SYMBOLATOR_SOURCE` in `server/ops/docker/jdk11-jammy/Dockerfile` for new commit hashes