= Kroki server

Kroki server acts as a gateway and provides a unified API on-top of diagrams libraries.

== How to update third-party dependencies

=== Ditaa (mini)

Since https://github.com/stathissideris/ditaa is unmaintained, we are using an active fork: https://github.com/yuzutech/ditaa-mini which is based on an active fork https://github.com/pepijnve/ditaa.

We are producing native binaries with GraalVM: https://github.com/yuzutech/ditaa-mini/releases.

When a new version is available, we need to :

. update the fork
. run the following workflow: https://github.com/yuzutech/ditaa-mini/actions/workflows/native-image-on-demand.yml
. update the argument variable `ARG DITAA_VERSION="x.y.z"` in `server/ops/docker/jdk11-jammy/Dockerfile`

=== PlantUML

We are producing native binaries with GraalVM: https://github.com/yuzutech/plantuml/releases

When a new version is available, we need to:

. update the fork
. run the following workflow: https://github.com/yuzutech/plantuml/actions/workflows/native-image-on-demand.yml
. update the argument variable `ARG PLANTUML_VERSION="x.y.z"` in `server/ops/docker/jdk11-jammy/Dockerfile`

=== UMLet

We are producing native binaries with GraalVM: https://github.com/yuzutech/umlet/releases

When a new version is available, we need to:

. update the fork
. run the following workflow: https://github.com/yuzutech/umlet/actions/workflows/release.yml
. update the argument variable `ARG UMLET_VERSION="x.y.z"` in `server/ops/docker/jdk11-jammy/Dockerfile`
