= BlockDiag (BlockDiag, SeqDiag, ActDiag, NwDiag, PacketDiag and RackDiag)
:uri-py-venv: https://docs.python.org/3/library/venv.html
:uri-py-releases: https://www.python.org/downloads/releases

Kroki companion server for diagrams libraries written in Python.

[NOTE]
====
The server accepts `POST` requests with the diagram sent as plain text.
It should only be used behind the Kroki gateway.
====

== Package

To get you started quickly, you can build a Docker image:

 $ sudo make package

Then you can run the server using the following command:

 $ sudo docker run --publish=8001:8001 yuzutech/kroki-blockdiag:latest

NOTE: We are using the `--publish` option to expose the container's port 8001 on the host's port 8001.

The server should be running and available at: http://localhost:8001/

== Local development

You will need to install {uri-py-releases}[Python 3.8+] on your machine.
We recommend {uri-py-venv}[creating a virtual environment] to install all the dependencies:

 $ python3.8 -m venv venv-py38

 $ venv-py38/bin/pip install -r requirements.txt
 $ venv-py38/bin/python src/server.py
