default:

package:
	docker build -f build-static-erd -t kroki-builder-static-erd .
	docker build -f build-static-svgbob -t kroki-builder-static-svgbob .
	docker build -f build-static-pikchr -t kroki-builder-static-pikchr .
