name: BlockDiag CI

on:
  push:
    paths:
      - 'blockdiag/**'
    branches:
      - main
  pull_request:
    paths:
      - 'blockdiag/**'
    branches:
      - '*'

jobs:
  blockdiag-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - name: Install BlockDiag
        run: make install
        working-directory: blockdiag
      - name: Test BlockDiag
        run: make test
        working-directory: blockdiag
