name: Mermaid CI

on:
  push:
    paths:
      - 'mermaid/**'
    branches:
      - main
  pull_request:
    paths:
      - 'mermaid/**'
    branches:
      - '*'

jobs:
  mermaid-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Setup Node.js 22'
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Node dependencies
        run: npm i
        working-directory: mermaid
      - name: Lint & tests
        run: npm run lint && npm t
        working-directory: mermaid
